name: announce release
on:
  release:
    types: [published]

jobs:
  discord-announcement:
    runs-on: ubuntu-latest
    steps:
      - name: notify discord
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          username: "GAMA Engine"
          # pointed to the raw usercontent link so discord can actually see it
          avatar_url: "https://raw.githubusercontent.com/popovicialinc/gama/main/%21assets/icon.png"
          color: "#5865F2"
          message: |
            # 🚀 **A new version of GAMA is live!**
            
            📱 **Version:** `${{ github.event.release.tag_name }}`
            
            📥 **Download the update here:**
            ${{ github.event.release.html_url }}